logging:
  level:
    root: INFO
    org.springframework.cloud.function: DEBUG


api:
  public:
    calendar:
      encodingKey: 2oZgjmX5voitj34%2FUianpw77PCv41zm5IQ8NDXUsDERsTAve9wzr1IDCQm7aJ2wtPMp5XH1Dy1b%2F3Rr0VQH0rw%3D%3D
      decodingKey: 2oZgjmX5voitj34/Uianpw77PCv41zm5IQ8NDXUsDERsTAve9wzr1IDCQm7aJ2wtPMp5XH1Dy1b/3Rr0VQH0rw==
      baseUrl: http://apis.data.go.kr/B090041/openapi/service/LrsrCldInfoService